version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    mode: 755
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 100
      runas: ec2-user